# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Vivado_Projects/MSGR/MSGR.srcs/sources_1/ip/FP_DIVIDE/FP_DIVIDE.xci
# IP: The module: 'FP_DIVIDE' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado_Projects/MSGR/MSGR.srcs/sources_1/ip/FP_DIVIDE/FP_DIVIDE_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FP_DIVIDE'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/Vivado_Projects/MSGR/MSGR.srcs/sources_1/ip/FP_DIVIDE/FP_DIVIDE.xci
# IP: The module: 'FP_DIVIDE' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado_Projects/MSGR/MSGR.srcs/sources_1/ip/FP_DIVIDE/FP_DIVIDE_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FP_DIVIDE'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
