# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/Counter/Counter.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Counter || ORIG_REF_NAME==Counter} -quiet] -quiet

# IP: ip/FP_ADDER/FP_ADDER.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FP_ADDER || ORIG_REF_NAME==FP_ADDER} -quiet] -quiet

# IP: ip/FP_MULT/FP_MULT.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FP_MULT || ORIG_REF_NAME==FP_MULT} -quiet] -quiet

# IP: ip/Counter_6/Counter_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Counter_6 || ORIG_REF_NAME==Counter_6} -quiet] -quiet

# IP: ip/Counter_13/Counter_13.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Counter_13 || ORIG_REF_NAME==Counter_13} -quiet] -quiet
